from django.utils import timezone

accommodation = [
    {
        "name": "Sorsogon Bayview Resort",
        "type": "resort",
        "description": "Seaside resort with panoramic views of Sorsogon Bay.",
        "image": "accommodations/bayview_resort.jpg",
        "contact_number": "+63 912 345 6789",
        "email": "info@bayviewresort.ph",
        "website": "https://bayviewresort.ph",
        "budget_category": "high",
        "address": "Poblacion, Sorsogon City, Sorsogon",
        "latitude": 12.9738,
        "longitude": 124.0045,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": True,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Casa Sorsogon Hotel",
        "type": "hotel",
        "description": "Modern hotel in the heart of Sorsogon City with comfortable rooms.",
        "image": "accommodations/casa_sorsogon.jpg",
        "contact_number": "+63 917 321 1122",
        "email": "contact@casasorsogon.ph",
        "website": "https://casasorsogon.ph",
        "budget_category": "medium",
        "address": "Magsaysay St., Sorsogon City, Sorsogon",
        "latitude": 12.9722,
        "longitude": 124.0078,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Bacon Beach Homestay",
        "type": "homestay",
        "description": "Cozy beachfront homestay near Bacon District beaches.",
        "image": "accommodations/bacon_homestay.jpg",
        "contact_number": "+63 921 556 7890",
        "email": "baconhomestay@gmail.com",
        "website": "",
        "budget_category": "low",
        "address": "Bacon, Sorsogon City, Sorsogon",
        "latitude": 12.9985,
        "longitude": 124.0316,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": False,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Gubat Coastal Inn",
        "type": "inn",
        "description": "Affordable lodging close to Gubat surfing spots and the beach.",
        "image": "accommodations/gubat_inn.jpg",
        "contact_number": "+63 918 777 6655",
        "email": "gubatcoastalinn@gmail.com",
        "website": "",
        "budget_category": "low",
        "address": "Poblacion, Gubat, Sorsogon",
        "latitude": 12.9217,
        "longitude": 124.1167,
        "parking_available": False,
        "wifi_available": True,
        "breakfast_included": False,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Donsol Eco Resort",
        "type": "resort",
        "description": "Eco-friendly resort popular for whale shark watching tours.",
        "image": "accommodations/donsol_eco_resort.jpg",
        "contact_number": "+63 917 345 4321",
        "email": "info@donsolresort.ph",
        "website": "https://donsolresort.ph",
        "budget_category": "medium",
        "address": "Dancalan, Donsol, Sorsogon",
        "latitude": 12.9100,
        "longitude": 123.5950,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": True,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Matnog Seafarers Inn",
        "type": "inn",
        "description": "Simple inn near the Matnog ferry terminal — great for travelers.",
        "image": "accommodations/matnog_inn.jpg",
        "contact_number": "+63 923 111 2233",
        "email": "matnoginn@gmail.com",
        "website": "",
        "budget_category": "low",
        "address": "Brgy. Poblacion, Matnog, Sorsogon",
        "latitude": 12.5847,
        "longitude": 124.0863,
        "parking_available": True,
        "wifi_available": False,
        "breakfast_included": False,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Bulan Garden Hotel",
        "type": "hotel",
        "description": "Garden-style hotel with function rooms and free breakfast.",
        "image": "accommodations/bulan_garden.jpg",
        "contact_number": "+63 917 222 3344",
        "email": "stay@bulangarden.ph",
        "website": "https://bulangarden.ph",
        "budget_category": "medium",
        "address": "Downtown Bulan, Sorsogon",
        "latitude": 12.6700,
        "longitude": 123.8770,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Bulusan Lakeview Lodge",
        "type": "bnb",
        "description": "Bed & Breakfast overlooking Bulusan Lake and Mt. Bulusan.",
        "image": "accommodations/bulusan_lakeview.jpg",
        "contact_number": "+63 918 333 4455",
        "email": "hello@lakeviewbulusan.ph",
        "website": "",
        "budget_category": "medium",
        "address": "Brgy. San Roque, Bulusan, Sorsogon",
        "latitude": 12.7516,
        "longitude": 123.8800,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Irosin Hills Resort",
        "type": "resort",
        "description": "Quiet riverside resort in Irosin with huts and cottages.",
        "image": "accommodations/irosin_hills.jpg",
        "contact_number": "+63 919 444 5566",
        "email": "info@irosinhills.ph",
        "website": "https://irosinhills.ph",
        "budget_category": "medium",
        "address": "Irosin, Sorsogon",
        "latitude": 12.7000,
        "longitude": 123.8500,
        "parking_available": True,
        "wifi_available": False,
        "breakfast_included": False,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Barcelona Surf Hostelry",
        "type": "hostel",
        "description": "Backpackers' hostel near Barcelona surf breaks.",
        "image": "accommodations/barcelona_hostel.jpg",
        "contact_number": "+63 921 555 6677",
        "email": "surf@barcelonahostel.ph",
        "website": "",
        "budget_category": "low",
        "address": "Barcelona, Sorsogon",
        "latitude": 12.8680,
        "longitude": 124.1370,
        "parking_available": False,
        "wifi_available": True,
        "breakfast_included": False,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Pilar Bay Lodge",
        "type": "inn",
        "description": "Small lodge with sea-access and local seafood restaurants nearby.",
        "image": "accommodations/pilar_bay.jpg",
        "contact_number": "+63 922 666 7788",
        "email": "booking@pilarbay.ph",
        "website": "",
        "budget_category": "low",
        "address": "Pilar, Sorsogon",
        "latitude": 12.9264,
        "longitude": 123.6710,
        "parking_available": True,
        "wifi_available": False,
        "breakfast_included": False,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Prieto Diaz Seaside Rooms",
        "type": "homestay",
        "description": "Family-run seaside rooms in Prieto Diaz, close to beaches.",
        "image": "accommodations/prietodiaz_seaside.jpg",
        "contact_number": "+63 923 777 8899",
        "email": "prietodiazstay@gmail.com",
        "website": "",
        "budget_category": "low",
        "address": "Prieto Diaz, Sorsogon",
        "latitude": 13.0415,
        "longitude": 124.1850,
        "parking_available": False,
        "wifi_available": False,
        "breakfast_included": False,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Casiguran Harbor Hotel",
        "type": "hotel",
        "description": "Comfortable hotel near the harbor and local markets.",
        "image": "accommodations/casiguran_harbor.jpg",
        "contact_number": "+63 924 888 9900",
        "email": "stay@casiguranharbor.ph",
        "website": "https://casiguranharbor.ph",
        "budget_category": "medium",
        "address": "Casiguran, Sorsogon",
        "latitude": 12.8725,
        "longitude": 124.0097,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Magallanes Traveller's Rest",
        "type": "inn",
        "description": "Budget-friendly rest stop for travelers passing through Magallanes.",
        "image": "accommodations/magallanes_rest.jpg",
        "contact_number": "+63 925 999 0011",
        "email": "magallanesrest@gmail.com",
        "website": "",
        "budget_category": "low",
        "address": "Magallanes, Sorsogon",
        "latitude": 12.8385,
        "longitude": 123.8183,
        "parking_available": True,
        "wifi_available": False,
        "breakfast_included": False,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Castilla Bayfront Stay",
        "type": "bnb",
        "description": "Small bed & breakfast overlooking Castilla coastline.",
        "image": "accommodations/castilla_bayfront.jpg",
        "contact_number": "+63 926 111 2234",
        "email": "bayfront@castillabnb.ph",
        "website": "",
        "budget_category": "medium",
        "address": "Castilla, Sorsogon",
        "latitude": 12.9448,
        "longitude": 123.8850,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Juban Hillside Inn",
        "type": "inn",
        "description": "Hillside rooms with views of the valley — quiet and restful.",
        "image": "accommodations/juban_hills.jpg",
        "contact_number": "+63 927 222 3345",
        "email": "info@jubanhills.ph",
        "website": "",
        "budget_category": "low",
        "address": "Juban, Sorsogon",
        "latitude": 12.8553,
        "longitude": 123.9670,
        "parking_available": True,
        "wifi_available": False,
        "breakfast_included": False,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Sorsogon City Traveller's Lodge",
        "type": "hotel",
        "description": "Conveniently located lodge for business and leisure guests.",
        "image": "accommodations/sorsogon_traveller.jpg",
        "contact_number": "+63 928 333 4456",
        "email": "reservations@sorsogontraveller.ph",
        "website": "https://sorsogontraveller.ph",
        "budget_category": "medium",
        "address": "Rizal St., Sorsogon City, Sorsogon",
        "latitude": 12.9710,
        "longitude": 124.0056,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": True,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Sea Breeze Homestay - Bulusan",
        "type": "homestay",
        "description": "Family homestay near sea and Bulusan natural spots.",
        "image": "accommodations/seabreeze_bulusan.jpg",
        "contact_number": "+63 929 444 5567",
        "email": "seabreezebulusan@gmail.com",
        "website": "",
        "budget_category": "low",
        "address": "Bulusan, Sorsogon",
        "latitude": 12.7516,
        "longitude": 123.8800,
        "parking_available": False,
        "wifi_available": False,
        "breakfast_included": False,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Sorsogon Heritage Guesthouse",
        "type": "bnb",
        "description": "Comfortable guesthouse near cultural sites of Sorsogon City.",
        "image": "accommodations/heritage_guesthouse.jpg",
        "contact_number": "+63 930 555 6678",
        "email": "stay@heritagesorsogon.ph",
        "website": "",
        "budget_category": "medium",
        "address": "Heritage District, Sorsogon City, Sorsogon",
        "latitude": 12.9745,
        "longitude": 124.0062,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
]

destination = [
    {
        "name": "Paguriran Island and Lagoon",
        "category": "nature",
        "description": "A scenic island-lagoon with clear waters, ideal for swimming and snorkeling.",
        "address": "Bacon, Sorsogon",
        "latitude": 12.9700,
        "longitude": 124.0500,
        "opening_time": "07:00",
        "closing_time": "17:00",
        "best_time_to_visit": "March-May",
        "avg_duration_minutes": 120,
        "entrance_fee": 50,
        "budget_category": "low",
        "nearest_transport": "Boat from Bacon port",
        "estimated_travel_time_minutes": 30,
        "parking_available": False,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": True,
        "status": "active",
    },
    {
        "name": "Libanon Beach",
        "category": "nature",
        "description": "Quiet, white sand beach in Gubat.",
        "address": "Gubat, Sorsogon",
        "latitude": 12.9200,
        "longitude": 124.1200,
        "opening_time": "06:00",
        "closing_time": "18:00",
        "best_time_to_visit": "December-April",
        "avg_duration_minutes": 180,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "By road from Gubat",
        "estimated_travel_time_minutes": 20,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": True,
        "status": "active",
    },
    {
        "name": "Bulusan Lake",
        "category": "nature",
        "description": "Lush volcanic lake in Bulusan Volcano Natural Park.",
        "address": "Bulusan, Sorsogon",
        "latitude": 12.7516,
        "longitude": 123.8800,
        "opening_time": "05:00",
        "closing_time": "18:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 90,
        "entrance_fee": 30,
        "budget_category": "low",
        "nearest_transport": "From Sorsogon City",
        "estimated_travel_time_minutes": 60,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Bagatao Island Lighthouse",
        "category": "historical",
        "description": "Historic lighthouse on Bagatao Island, guiding ships entering Sorsogon Bay.",
        "address": "Bagatao Island, Magallanes, Sorsogon",
        "latitude": 12.7950,
        "longitude": 123.7850,
        "opening_time": "08:00",
        "closing_time": "17:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 60,
        "entrance_fee": 20,
        "budget_category": "low",
        "nearest_transport": "Boat from Magallanes",
        "estimated_travel_time_minutes": 45,
        "parking_available": False,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Barcelona Coral Church & Ruins Park",
        "category": "cultural",
        "description": "Old coral stone church and ruins in Barcelona, Sorsogon.",
        "address": "Barcelona, Sorsogon",
        "latitude": 12.8680,
        "longitude": 124.1370,
        "opening_time": "06:00",
        "closing_time": "18:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 60,
        "entrance_fee": 10,
        "budget_category": "low",
        "nearest_transport": "Road via Barcelona",
        "estimated_travel_time_minutes": 30,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Sorsogon Capitol Park",
        "category": "cultural",
        "description": "Public park and landmark surrounding the provincial capitol building.",
        "address": "Sorsogon City",
        "latitude": 12.9700,
        "longitude": 124.0000,
        "opening_time": "00:00",
        "closing_time": "23:59",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 30,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "In city center",
        "estimated_travel_time_minutes": 5,
        "parking_available": True,
        "wheelchair_friendly": True,
        "kid_friendly": True,
        "senior_friendly": True,
        "status": "active",
    },
    {
        "name": "Sorsogon Sports Arena",
        "category": "other",
        "description": "New sports facility in Sorsogon City.",
        "address": "Sorsogon City",
        "latitude": 12.9720,
        "longitude": 124.0010,
        "opening_time": "06:00",
        "closing_time": "22:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 60,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "City roads",
        "estimated_travel_time_minutes": 10,
        "parking_available": True,
        "wheelchair_friendly": True,
        "kid_friendly": True,
        "senior_friendly": True,
        "status": "active",
    },
    {
        "name": "Pipa de Playa (Gubat)",
        "category": "nature",
        "description": "Secluded beach spot in Gubat.",
        "address": "Gubat, Sorsogon",
        "latitude": 12.9150,
        "longitude": 124.1150,
        "opening_time": "06:00",
        "closing_time": "18:00",
        "best_time_to_visit": "December-April",
        "avg_duration_minutes": 120,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "By road from Gubat",
        "estimated_travel_time_minutes": 25,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Subic White Beach",
        "category": "nature",
        "description": "White sandy beach popular among local tourists.",
        "address": "Matnog, Sorsogon",
        "latitude": 12.5800,
        "longitude": 124.0850,
        "opening_time": "05:00",
        "closing_time": "19:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 180,
        "entrance_fee": 30,
        "budget_category": "low",
        "nearest_transport": "Road from Matnog",
        "estimated_travel_time_minutes": 60,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Donsol Whale Shark Interaction",
        "category": "adventure",
        "description": "Swim with whale sharks in Donsol (seasonal).",
        "address": "Donsol, Sorsogon",
        "latitude": 12.9100,
        "longitude": 123.6000,
        "opening_time": "08:00",
        "closing_time": "16:00",
        "best_time_to_visit": "December-May",
        "avg_duration_minutes": 240,
        "entrance_fee": 500,
        "budget_category": "medium",
        "nearest_transport": "From Donsol town",
        "estimated_travel_time_minutes": 20,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Lake Aguingay",
        "category": "nature",
        "description": "Seasonal crater lake near Bulusan.",
        "address": "Bulusan, Sorsogon",
        "latitude": 12.7550,
        "longitude": 123.8850,
        "opening_time": "06:00",
        "closing_time": "18:00",
        "best_time_to_visit": "Rainy season",
        "avg_duration_minutes": 120,
        "entrance_fee": 20,
        "budget_category": "low",
        "nearest_transport": "From Bulusan Lake trails",
        "estimated_travel_time_minutes": 45,
        "parking_available": False,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Parola Beach & Lighthouse (Bagatao Island)",
        "category": "nature",
        "description": "Beach area with lighthouse on Bagatao Island.",
        "address": "Bagatao Island, Magallanes, Sorsogon",
        "latitude": 12.7950,
        "longitude": 123.7850,
        "opening_time": "06:00",
        "closing_time": "18:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 90,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "Boat from Magallanes",
        "estimated_travel_time_minutes": 45,
        "parking_available": False,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Pepita Park",
        "category": "cultural",
        "description": "Public park in Sorsogon City.",
        "address": "Sorsogon City",
        "latitude": 12.9690,
        "longitude": 124.0020,
        "opening_time": "00:00",
        "closing_time": "23:59",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 30,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "City roads",
        "estimated_travel_time_minutes": 5,
        "parking_available": True,
        "wheelchair_friendly": True,
        "kid_friendly": True,
        "senior_friendly": True,
        "status": "active",
    },
    {
        "name": "Ilawod Beach",
        "category": "nature",
        "description": "Beach in Sorsogon province.",
        "address": "Matnog, Sorsogon",
        "latitude": 12.5820,
        "longitude": 124.0880,
        "opening_time": "05:00",
        "closing_time": "18:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 180,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "Road from Matnog",
        "estimated_travel_time_minutes": 50,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Rompeolas (Breakwater) Sorsogon City",
        "category": "other",
        "description": "Coastal promenade / breakwater in Sorsogon City.",
        "address": "Sorsogon City",
        "latitude": 12.9680,
        "longitude": 124.0030,
        "opening_time": "00:00",
        "closing_time": "23:59",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 45,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "City roads",
        "estimated_travel_time_minutes": 10,
        "parking_available": False,
        "wheelchair_friendly": True,
        "kid_friendly": True,
        "senior_friendly": True,
        "status": "active",
    },
    {
        "name": "Dancalan Bay / Beach",
        "category": "nature",
        "description": "Peaceful bay and beach in Dancalan area.",
        "address": "Dancalan, Donsol, Sorsogon",
        "latitude": 12.9050,
        "longitude": 123.5980,
        "opening_time": "06:00",
        "closing_time": "18:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 120,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "Road from Donsol",
        "estimated_travel_time_minutes": 60,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "SM City Sorsogon (Mall / Shopping)",
        "category": "shopping",
        "description": "Large mall for shopping in Sorsogon City.",
        "address": "Sorsogon City",
        "latitude": 12.9712,
        "longitude": 123.9295,
        "opening_time": "10:00",
        "closing_time": "21:00",
        "best_time_to_visit": "Evenings / weekends",
        "avg_duration_minutes": 120,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "City roads",
        "estimated_travel_time_minutes": 10,
        "parking_available": True,
        "wheelchair_friendly": True,
        "kid_friendly": True,
        "senior_friendly": True,
        "status": "active",
    },
    {
        "name": "Cultural / Museo Sorsogon",
        "category": "cultural",
        "description": "Local museum showcasing history and culture of Sorsogon.",
        "address": "Sorsogon City",
        "latitude": 12.9700,
        "longitude": 124.0005,
        "opening_time": "08:00",
        "closing_time": "17:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 60,
        "entrance_fee": 20,
        "budget_category": "low",
        "nearest_transport": "City roads",
        "estimated_travel_time_minutes": 5,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Nasipit Falls",
        "category": "nature",
        "description": "Waterfall in Bulusan area (one of the falls in Bulusan NP).",
        "address": "Bulusan, Sorsogon",
        "latitude": 12.7580,
        "longitude": 123.8920,
        "opening_time": "06:00",
        "closing_time": "17:00",
        "best_time_to_visit": "Rainy season",
        "avg_duration_minutes": 90,
        "entrance_fee": 20,
        "budget_category": "low",
        "nearest_transport": "From Bulusan trails",
        "estimated_travel_time_minutes": 30,
        "parking_available": False,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
]

hubs = [
    {
        'name': 'Sorsogon Integrated Terminal Exchange (SITEX)',
        'hub_type': 'bus_stop',
        'description': 'Main inter-provincial bus terminal in Sorsogon City, near SM Sorsogon.',
        'address': 'Sorsogon City, Sorsogon Province, Bicol Region',
        'latitude': 12.9712,
        'longitude': 123.9295,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Bulan Integrated Terminal',
        'hub_type': 'bus_stop',
        'description': 'Provincial bus and van terminal located at Bulan town proper.',
        'address': 'Bulan, Sorsogon Province, Bicol Region',
        'latitude': 12.6700,
        'longitude': 123.8770,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Matnog Port Ferry Terminal',
        'hub_type': 'ferry_terminal',
        'description': 'Major ferry terminal connecting Luzon to Samar and the Visayas.',
        'address': 'Matnog Port Area, Matnog, Sorsogon Province',
        'latitude': 12.5847,
        'longitude': 124.0863,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Pilar Port Terminal',
        'hub_type': 'ferry_terminal',
        'description': 'Port terminal serving Masbate and other nearby island routes.',
        'address': 'Binanuahan, Pilar, Sorsogon Province',
        'latitude': 12.9264,
        'longitude': 123.6710,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Donsol Transport Terminal',
        'hub_type': 'bus_stop',
        'description': 'Bus and van terminal in Donsol, known for whale shark tourism.',
        'address': 'Donsol, Sorsogon Province, Bicol Region',
        'latitude': 12.9050,
        'longitude': 123.5950,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Gubat Transport Terminal',
        'hub_type': 'bus_stop',
        'description': 'Bus and jeepney terminal at Gubat town proper.',
        'address': 'Gubat, Sorsogon Province, Bicol Region',
        'latitude': 12.9217,
        'longitude': 124.1167,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Irosin Transport Terminal',
        'hub_type': 'bus_stop',
        'description': 'Inter-municipal terminal at Irosin town proper.',
        'address': 'Irosin, Sorsogon Province, Bicol Region',
        'latitude': 12.7000,
        'longitude': 123.8500,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Casiguran Highway Stop',
        'hub_type': 'bus_stop',
        'description': 'Main bus stop along the Maharlika Highway in Casiguran.',
        'address': 'Casiguran, Sorsogon Province, Bicol Region',
        'latitude': 12.8725,
        'longitude': 124.0097,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Bacon District Jeepney Terminal',
        'hub_type': 'jeepney_stop',
        'description': 'Jeepney terminal in Bacon District, connecting Sorsogon barangays.',
        'address': 'Bacon District, Sorsogon City, Sorsogon Province',
        'latitude': 12.9985,
        'longitude': 124.0316,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Sirangan Tricycle Hub',
        'hub_type': 'tricycle_stop',
        'description': 'Tricycle hub serving the downtown Sirangan area in Sorsogon City.',
        'address': 'Sirangan, Sorsogon City, Sorsogon Province',
        'latitude': 12.9650,
        'longitude': 124.0000,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Barcelona Jeepney Stop',
        'hub_type': 'jeepney_stop',
        'description': 'Jeepney stop in Barcelona municipality along coastal route.',
        'address': 'Barcelona, Sorsogon Province, Bicol Region',
        'latitude': 12.8680,
        'longitude': 124.1370,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Bulusan Terminal',
        'hub_type': 'bus_stop',
        'description': 'Transport hub for Bulusan town near Bulusan Volcano Natural Park.',
        'address': 'Bulusan, Sorsogon Province, Bicol Region',
        'latitude': 12.7516,
        'longitude': 123.8800,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Matnog Parking Area – Ferry Access',
        'hub_type': 'parking_area',
        'description': 'Parking area for trucks and buses near Matnog ferry terminal.',
        'address': 'Matnog, Sorsogon Province, Bicol Region',
        'latitude': 12.5847,
        'longitude': 124.0863,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Sorsogon City East Tricycle Terminal',
        'hub_type': 'tricycle_stop',
        'description': 'Tricycle terminal serving East District barangays.',
        'address': 'East District, Sorsogon City, Sorsogon Province',
        'latitude': 12.9750,
        'longitude': 124.0080,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Juban Transport Terminal',
        'hub_type': 'bus_stop',
        'description': 'Transport terminal in Juban municipality, connecting north to Sorsogon City.',
        'address': 'Juban, Sorsogon Province, Bicol Region',
        'latitude': 12.8553,
        'longitude': 123.9670,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Prieto Diaz Jeepney Terminal',
        'hub_type': 'jeepney_stop',
        'description': 'Jeepney terminal at Prieto Diaz town proper, coastal side.',
        'address': 'Prieto Diaz, Sorsogon Province, Bicol Region',
        'latitude': 13.0415,
        'longitude': 124.1850,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Magallanes Port Terminal',
        'hub_type': 'ferry_terminal',
        'description': 'Small port terminal for local ferry routes in Magallanes, Sorsogon.',
        'address': 'Magallanes, Sorsogon Province, Bicol Region',
        'latitude': 12.8385,
        'longitude': 123.8183,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Castilla Bus Stop',
        'hub_type': 'bus_stop',
        'description': 'Main bus stop area along Maharlika Highway in Castilla municipality.',
        'address': 'Castilla, Sorsogon Province, Bicol Region',
        'latitude': 12.9448,
        'longitude': 123.8850,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Gubat Tricycle Stop',
        'hub_type': 'tricycle_stop',
        'description': 'Tricycle stop near Gubat town plaza serving local barangays.',
        'address': 'Gubat, Sorsogon Province, Bicol Region',
        'latitude': 12.9217,
        'longitude': 124.1167,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
    {
        'name': 'Sorsogon City Parking Area – SM Complex',
        'hub_type': 'parking_area',
        'description': 'Public parking area near SM Sorsogon complex and SITEX terminal.',
        'address': 'SM Sorsogon Complex, Sorsogon City, Sorsogon Province',
        'latitude': 12.9712,
        'longitude': 123.9295,
        'status': 'active',
        'created_at': timezone.now(),
        'updated_at': timezone.now(),
        'is_active': True,
    },
]

"""
trip duration
pax
budget category

starting point 
transportation mode

interest categories
pace preference

has children
has seniors
has disabilities
has pet 

include accommmodation
accommodation preferences

max travel time

must visit destination
exclude categories


"""