# Generated by Django 5.2.6 on 2025-10-27 04:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_userprofile_user'),  # <--- add this
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('inn', 'Inn'), ('homestay', 'Homestay'), ('hostel', 'Hostel'), ('bnb', 'Bed & Breakfast'), ('others', 'Others')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accommodations/')),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('budget_category', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('parking_available', models.BooleanField(default=False)),
                ('wifi_available', models.BooleanField(default=False)),
                ('breakfast_included', models.BooleanField(default=False)),
                ('air_conditioned', models.BooleanField(default=False)),
                ('wheelchair_friendly', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Temporarily Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Accommodation',
                'verbose_name_plural': 'Accommodations',
                'ordering': ['-created_at'],
            },
        ),
    ]
