# accommodation/migrations/0002_seed_accommodations.py
from django.db import migrations
from django.utils import timezone

def create_initial_accommodations(apps, schema_editor):
    Accommodation = apps.get_model('accommodation', 'Accommodation')

    accommodations_data = [
    {
        "name": "Sorsogon Bayview Resort",
        "type": "resort",
        "description": "Seaside resort with panoramic views of Sorsogon Bay.",
        "contact_number": "+63 912 345 6789",
        "email": "info@bayviewresort.ph",
        "website": "https://bayviewresort.ph",
        "budget_category": "high",
        "address": "Poblacion, Sorsogon City, Sorsogon",
        "latitude": 12.9738,
        "longitude": 124.0045,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": True,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Casa Sorsogon Hotel",
        "type": "hotel",
        "description": "Modern hotel in the heart of Sorsogon City with comfortable rooms.",
        "contact_number": "+63 917 321 1122",
        "email": "contact@casasorsogon.ph",
        "website": "https://casasorsogon.ph",
        "budget_category": "medium",
        "address": "Magsaysay St., Sorsogon City, Sorsogon",
        "latitude": 12.9722,
        "longitude": 124.0078,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Bacon Beach Homestay",
        "type": "homestay",
        "description": "Cozy beachfront homestay near Bacon District beaches.",
        "contact_number": "+63 921 556 7890",
        "email": "baconhomestay@gmail.com",
        "website": "",
        "budget_category": "low",
        "address": "Bacon, Sorsogon City, Sorsogon",
        "latitude": 12.9985,
        "longitude": 124.0316,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": False,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Gubat Coastal Inn",
        "type": "inn",
        "description": "Affordable lodging close to Gubat surfing spots and the beach.",
        "contact_number": "+63 918 777 6655",
        "email": "gubatcoastalinn@gmail.com",
        "website": "",
        "budget_category": "low",
        "address": "Poblacion, Gubat, Sorsogon",
        "latitude": 12.9217,
        "longitude": 124.1167,
        "parking_available": False,
        "wifi_available": True,
        "breakfast_included": False,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Donsol Eco Resort",
        "type": "resort",
        "description": "Eco-friendly resort popular for whale shark watching tours.",
        "contact_number": "+63 917 345 4321",
        "email": "info@donsolresort.ph",
        "website": "https://donsolresort.ph",
        "budget_category": "medium",
        "address": "Dancalan, Donsol, Sorsogon",
        "latitude": 12.9100,
        "longitude": 123.5950,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": True,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Matnog Seafarers Inn",
        "type": "inn",
        "description": "Simple inn near the Matnog ferry terminal — great for travelers.",
        "contact_number": "+63 923 111 2233",
        "email": "matnoginn@gmail.com",
        "website": "",
        "budget_category": "low",
        "address": "Brgy. Poblacion, Matnog, Sorsogon",
        "latitude": 12.5847,
        "longitude": 124.0863,
        "parking_available": True,
        "wifi_available": False,
        "breakfast_included": False,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Bulan Garden Hotel",
        "type": "hotel",
        "description": "Garden-style hotel with function rooms and free breakfast.",
        "contact_number": "+63 917 222 3344",
        "email": "stay@bulangarden.ph",
        "website": "https://bulangarden.ph",
        "budget_category": "medium",
        "address": "Downtown Bulan, Sorsogon",
        "latitude": 12.6700,
        "longitude": 123.8770,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Bulusan Lakeview Lodge",
        "type": "bnb",
        "description": "Bed & Breakfast overlooking Bulusan Lake and Mt. Bulusan.",
        "contact_number": "+63 918 333 4455",
        "email": "hello@lakeviewbulusan.ph",
        "website": "",
        "budget_category": "medium",
        "address": "Brgy. San Roque, Bulusan, Sorsogon",
        "latitude": 12.7516,
        "longitude": 123.8800,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Irosin Hills Resort",
        "type": "resort",
        "description": "Quiet riverside resort in Irosin with huts and cottages.",
        "contact_number": "+63 919 444 5566",
        "email": "info@irosinhills.ph",
        "website": "https://irosinhills.ph",
        "budget_category": "medium",
        "address": "Irosin, Sorsogon",
        "latitude": 12.7000,
        "longitude": 123.8500,
        "parking_available": True,
        "wifi_available": False,
        "breakfast_included": False,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Barcelona Surf Hostelry",
        "type": "hostel",
        "description": "Backpackers' hostel near Barcelona surf breaks.",
        "contact_number": "+63 921 555 6677",
        "email": "surf@barcelonahostel.ph",
        "website": "",
        "budget_category": "low",
        "address": "Barcelona, Sorsogon",
        "latitude": 12.8680,
        "longitude": 124.1370,
        "parking_available": False,
        "wifi_available": True,
        "breakfast_included": False,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Pilar Bay Lodge",
        "type": "inn",
        "description": "Small lodge with sea-access and local seafood restaurants nearby.",
        "contact_number": "+63 922 666 7788",
        "email": "booking@pilarbay.ph",
        "website": "",
        "budget_category": "low",
        "address": "Pilar, Sorsogon",
        "latitude": 12.9264,
        "longitude": 123.6710,
        "parking_available": True,
        "wifi_available": False,
        "breakfast_included": False,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Prieto Diaz Seaside Rooms",
        "type": "homestay",
        "description": "Family-run seaside rooms in Prieto Diaz, close to beaches.",
        "contact_number": "+63 923 777 8899",
        "email": "prietodiazstay@gmail.com",
        "website": "",
        "budget_category": "low",
        "address": "Prieto Diaz, Sorsogon",
        "latitude": 13.0415,
        "longitude": 124.1850,
        "parking_available": False,
        "wifi_available": False,
        "breakfast_included": False,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Casiguran Harbor Hotel",
        "type": "hotel",
        "description": "Comfortable hotel near the harbor and local markets.",
        "contact_number": "+63 924 888 9900",
        "email": "stay@casiguranharbor.ph",
        "website": "https://casiguranharbor.ph",
        "budget_category": "medium",
        "address": "Casiguran, Sorsogon",
        "latitude": 12.8725,
        "longitude": 124.0097,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Magallanes Traveller's Rest",
        "type": "inn",
        "description": "Budget-friendly rest stop for travelers passing through Magallanes.",
        "contact_number": "+63 925 999 0011",
        "email": "magallanesrest@gmail.com",
        "website": "",
        "budget_category": "low",
        "address": "Magallanes, Sorsogon",
        "latitude": 12.8385,
        "longitude": 123.8183,
        "parking_available": True,
        "wifi_available": False,
        "breakfast_included": False,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Castilla Bayfront Stay",
        "type": "bnb",
        "description": "Small bed & breakfast overlooking Castilla coastline.",
        "contact_number": "+63 926 111 2234",
        "email": "bayfront@castillabnb.ph",
        "website": "",
        "budget_category": "medium",
        "address": "Castilla, Sorsogon",
        "latitude": 12.9448,
        "longitude": 123.8850,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Juban Hillside Inn",
        "type": "inn",
        "description": "Hillside rooms with views of the valley — quiet and restful.",
        "contact_number": "+63 927 222 3345",
        "email": "info@jubanhills.ph",
        "website": "",
        "budget_category": "low",
        "address": "Juban, Sorsogon",
        "latitude": 12.8553,
        "longitude": 123.9670,
        "parking_available": True,
        "wifi_available": False,
        "breakfast_included": False,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Sorsogon City Traveller's Lodge",
        "type": "hotel",
        "description": "Conveniently located lodge for business and leisure guests.",
        "contact_number": "+63 928 333 4456",
        "email": "reservations@sorsogontraveller.ph",
        "website": "https://sorsogontraveller.ph",
        "budget_category": "medium",
        "address": "Rizal St., Sorsogon City, Sorsogon",
        "latitude": 12.9710,
        "longitude": 124.0056,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": True,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Sea Breeze Homestay - Bulusan",
        "type": "homestay",
        "description": "Family homestay near sea and Bulusan natural spots.",
        "contact_number": "+63 929 444 5567",
        "email": "seabreezebulusan@gmail.com",
        "website": "",
        "budget_category": "low",
        "address": "Bulusan, Sorsogon",
        "latitude": 12.7516,
        "longitude": 123.8800,
        "parking_available": False,
        "wifi_available": False,
        "breakfast_included": False,
        "air_conditioned": False,
        "wheelchair_friendly": False,
        "pet_friendly": True,
        "status": "active",
        "created_at": timezone.now(),
    },
    {
        "name": "Sorsogon Heritage Guesthouse",
        "type": "bnb",
        "description": "Comfortable guesthouse near cultural sites of Sorsogon City.",
        "contact_number": "+63 930 555 6678",
        "email": "stay@heritagesorsogon.ph",
        "website": "",
        "budget_category": "medium",
        "address": "Heritage District, Sorsogon City, Sorsogon",
        "latitude": 12.9745,
        "longitude": 124.0062,
        "parking_available": True,
        "wifi_available": True,
        "breakfast_included": True,
        "air_conditioned": True,
        "wheelchair_friendly": False,
        "pet_friendly": False,
        "status": "active",
        "created_at": timezone.now(),
    },
]

    # Create entries (exactly 20)
    for data in accommodations_data:
        Accommodation.objects.create(**data)


def delete_initial_accommodations(apps, schema_editor):
    Accommodation = apps.get_model('accommodation', 'Accommodation')
    # Delete only the seeded entries by name to avoid removing other data.
    seeded_names = [
        "Sorsogon Bayview Resort",
        "Casa Sorsogon Hotel",
        "Bacon Beach Homestay",
        "Gubat Coastal Inn",
        "Donsol Eco Resort",
        "Matnog Seafarers Inn",
        "Bulan Garden Hotel",
        "Bulusan Lakeview Lodge",
        "Irosin Hills Resort",
        "Barcelona Surf Hostelry",
        "Pilar Bay Lodge",
        "Prieto Diaz Seaside Rooms",
        "Casiguran Harbor Hotel",
        "Magallanes Traveller's Rest",
        "Castilla Bayfront Stay",
        "Juban Hillside Inn",
        "Sorsogon City Traveller's Lodge",
        "Sea Breeze Homestay - Bulusan",
        "Sorsogon Heritage Guesthouse",
        "Bacon Beach Homestay"  # NOTE: already included; kept for safety check (duplicate names handled)
    ]
    # Ensure unique names
    seeded_names = list(dict.fromkeys(seeded_names))
    Accommodation.objects.filter(name__in=seeded_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_accommodations, delete_initial_accommodations),
    ]
