# Generated by Django 5.2.6 on 2025-10-27 05:20

from django.db import migrations

def seed_accommodations_creator(apps, schema_editor):
    Accommodation = apps.get_model('accommodation', 'Accommodation')
    User = apps.get_model('auth', 'User')

    # Get or create a default user to assign as creator
    user = User.objects.filter(is_superuser=True).first()
    if not user:
        user = User.objects.create_user(username='admin', password='adminpass', first_name="Admin", last_name="User", email="admin@admin.com", is_staff=True, is_superuser=True)
        # create UserProfile
        UserProfile = apps.get_model('authentication', 'UserProfile')
        UserProfile.objects.create(user=user, first_time_login=True)

    # Update existing accommodations to have a created_by user
    Accommodation.objects.filter(created_by__isnull=True).update(created_by=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_accommodation_created_by'),
        ('authentication', '0001_initial'),  # <--- add this
    ]

    operations = [
        migrations.RunPython(seed_accommodations_creator),
    ]
