# Generated by Django 5.2.6 on 2025-10-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_seed_accommodations_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
