# Generated by Django 5.2.6 on 2025-10-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0005_alter_accommodation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True),
        ),
    ]
