# Generated by Django 5.2.6 on 2025-10-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0006_alter_accommodation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True),
        ),
    ]
