# Generated by Django 5.2.6 on 2025-12-11 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0007_alter_accommodation_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodations/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='accommodation.accommodation')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
