# Generated by Django 5.2.6 on 2025-11-24 20:50
from datetime import timedelta

from django.db import migrations
from django.utils import timezone


def populate_sample_data(apps, schema_editor):
    Feedback = apps.get_model('general', 'Feedback')
    Announcement = apps.get_model('general', 'Announcement')
    Guest = apps.get_model('general', 'Guest')
    Destination = apps.get_model('destination', 'Destination')

    now = timezone.now()

    # Sample Feedbacks (8 entries)
    feedbacks = [
        {
            'name': 'Maria Santos',
            'email': 'maria.santos@email.com',
            'category': 'praise',
            'subject': 'Amazing Tourism Portal!',
            'message': 'This website made planning my Sorsogon trip so easy. The itinerary planner is fantastic!',
            'status': 'reviewed',
        },
        {
            'name': 'John Reyes',
            'email': 'john.reyes@email.com',
            'category': 'suggestion',
            'subject': 'Add More Filters',
            'message': 'It would be great to have filters for kid-friendly destinations and pet-friendly accommodations.',
            'status': 'pending',
        },
        {
            'name': 'Ana Garcia',
            'email': 'ana.garcia@email.com',
            'category': 'general',
            'subject': 'Great Resource for Tourists',
            'message': 'Found all the information I needed about Donsol whale shark watching. Very helpful!',
            'status': 'resolved',
        },
        {
            'name': 'Carlos Mendoza',
            'email': 'carlos.m@email.com',
            'category': 'bug',
            'subject': 'Map Not Loading',
            'message': 'The interactive map on the destinations page is not loading on my mobile browser.',
            'status': 'resolved',
        },
        {
            'name': 'Lisa Tan',
            'email': 'lisa.tan@email.com',
            'category': 'suggestion',
            'subject': 'Add Local Food Guide',
            'message': 'Please add a section for local Sorsogon cuisine and recommended restaurants.',
            'status': 'pending',
        },
        {
            'name': 'Roberto Cruz',
            'email': 'roberto.cruz@email.com',
            'category': 'praise',
            'subject': 'Best Trip Planning Tool',
            'message': 'The rule-based itinerary planner saved me hours of research. Highly recommended!',
            'status': 'reviewed',
        },
        {
            'name': 'Michelle Lim',
            'email': 'michelle.lim@email.com',
            'category': 'complaint',
            'subject': 'Outdated Accommodation Info',
            'message': 'Some of the accommodation prices listed are outdated. Please update them.',
            'status': 'pending',
        },
        {
            'name': 'David Flores',
            'email': 'david.flores@email.com',
            'category': 'general',
            'subject': 'Transportation Options',
            'message': 'Would love to see more details about public transportation schedules between municipalities.',
            'status': 'pending',
        },
    ]

    for fb in feedbacks:
        Feedback.objects.create(**fb)

    # Sample Announcements (7 entries)
    announcements = [
        {
            'title': 'Whale Shark Season 2025 Now Open',
            'slug': 'whale-shark-season-2025-now-open',
            'content': 'The whale shark interaction season in Donsol is officially open! Experience swimming with these gentle giants from November through June. Book your butanding interaction early to secure your spot.',
            'excerpt': 'Donsol whale shark season is now open for 2025. Book your butanding experience today!',
            'priority': 'high',
            'is_published': True,
            'is_featured': True,
            'publish_date': now - timedelta(days=5),
        },
        {
            'title': 'New Eco-Tourism Trail in Bulusan',
            'slug': 'new-eco-tourism-trail-bulusan',
            'content': 'Discover the newly opened eco-tourism trail around Bulusan Lake. The trail features stunning views of Bulusan Volcano, diverse wildlife, and serene lake views. Guided tours available daily.',
            'excerpt': 'Explore the new eco-tourism trail at Bulusan Lake with guided tours.',
            'priority': 'normal',
            'is_published': True,
            'is_featured': False,
            'publish_date': now - timedelta(days=10),
        },
        {
            'title': 'Kasanggayahan Festival 2025',
            'slug': 'kasanggayahan-festival-2025',
            'content': 'Join us for the annual Kasanggayahan Festival celebrating Sorsogon\'s founding anniversary. Enjoy street dancing, food fairs, cultural shows, and fireworks throughout October.',
            'excerpt': 'Celebrate Sorsogon\'s founding anniversary at the Kasanggayahan Festival.',
            'priority': 'urgent',
            'is_published': True,
            'is_featured': True,
            'publish_date': now - timedelta(days=2),
        },
        {
            'title': 'Road Improvement Notice: Irosin-Bulusan Route',
            'slug': 'road-improvement-irosin-bulusan',
            'content': 'Please be advised that road improvements are ongoing along the Irosin-Bulusan route. Expect minor delays. Alternative routes are available via Juban.',
            'excerpt': 'Road work advisory for travelers heading to Bulusan area.',
            'priority': 'high',
            'is_published': True,
            'is_featured': False,
            'publish_date': now - timedelta(days=3),
        },
        {
            'title': 'New Partner Accommodations Added',
            'slug': 'new-partner-accommodations-added',
            'content': 'We have added 15 new partner accommodations across Sorsogon Province. From budget-friendly homestays to premium resorts, find the perfect place for your stay.',
            'excerpt': 'Discover new accommodation options now available on our portal.',
            'priority': 'normal',
            'is_published': True,
            'is_featured': False,
            'publish_date': now - timedelta(days=15),
        },
        {
            'title': 'Surfing Competition at Gubat Beach',
            'slug': 'surfing-competition-gubat-beach',
            'content': 'Watch the best surfers compete at the annual Gubat Surfing Competition. Free admission for spectators. Food stalls and activities available for the whole family.',
            'excerpt': 'Annual surfing competition coming to Gubat Beach.',
            'priority': 'normal',
            'is_published': False,
            'is_featured': False,
            'publish_date': now + timedelta(days=30),
        },
        {
            'title': 'Portal Maintenance Scheduled',
            'slug': 'portal-maintenance-scheduled',
            'content': 'The Sorsogon Tourism Portal will undergo scheduled maintenance on December 1, 2025 from 2:00 AM to 6:00 AM. Some features may be temporarily unavailable.',
            'excerpt': 'Brief maintenance window scheduled for portal improvements.',
            'priority': 'low',
            'is_published': True,
            'is_featured': False,
            'publish_date': now - timedelta(days=1),
        },
    ]

    for ann in announcements:
        Announcement.objects.create(**ann)

    # Sample Guests (10 entries) - linked to existing destinations
    destinations = list(Destination.objects.all()[:5])

    if destinations:
        guests_data = [
            {'name': 'Emily Chen', 'email': 'emily.chen@email.com', 'phone': '+63 912 345 6789',
             'location': 'Manila, Philippines', 'notes': 'First time visiting Sorsogon. Loved the whale sharks!'},
            {'name': 'Michael Johnson', 'email': 'michael.j@email.com', 'phone': '+1 555 123 4567',
             'location': 'California, USA', 'notes': 'Traveling with family of 4. Kids enjoyed the beaches.'},
            {'name': 'Yuki Tanaka', 'email': 'yuki.tanaka@email.com', 'phone': '+81 90 1234 5678',
             'location': 'Tokyo, Japan', 'notes': 'Solo backpacker exploring Bicol region.'},
            {'name': 'Sarah Williams', 'email': 'sarah.w@email.com', 'phone': '+44 7911 123456',
             'location': 'London, UK', 'notes': 'Photography enthusiast. Captured amazing shots of Bulusan.'},
            {'name': 'Pedro Gonzales', 'email': 'pedro.g@email.com', 'phone': '+63 917 876 5432',
             'location': 'Cebu, Philippines', 'notes': 'Weekend getaway with friends.'},
            {'name': 'Anna Mueller', 'email': 'anna.mueller@email.com', 'phone': '+49 151 12345678',
             'location': 'Berlin, Germany', 'notes': 'Eco-tourism enthusiast. Loved the natural hot springs.'},
            {'name': 'James Park', 'email': 'james.park@email.com', 'phone': '+82 10 1234 5678',
             'location': 'Seoul, South Korea', 'notes': 'Honeymoon trip. Beautiful sunset views!'},
            {'name': 'Isabella Rossi', 'email': 'isabella.r@email.com', 'phone': '+39 333 123 4567',
             'location': 'Rome, Italy', 'notes': 'Food lover. Enjoyed local Bicolano cuisine.'},
            {'name': 'Mark Thompson', 'email': 'mark.t@email.com', 'phone': '+61 412 345 678',
             'location': 'Sydney, Australia', 'notes': 'Surfer visiting Gubat beaches.'},
            {'name': 'Sofia Martinez', 'email': 'sofia.m@email.com', 'phone': '+34 612 345 678',
             'location': 'Barcelona, Spain', 'notes': 'Travel blogger covering hidden gems in Philippines.'},
        ]

        for i, guest_data in enumerate(guests_data):
            dest = destinations[i % len(destinations)]
            Guest.objects.create(
                destination=dest,
                name=guest_data['name'],
                email=guest_data['email'],
                phone=guest_data['phone'],
                location=guest_data['location'],
                visit_date=now.date() - timedelta(days=(i * 7)),
                notes=guest_data['notes'],
            )


def reverse_sample_data(apps, schema_editor):
    Feedback = apps.get_model('general', 'Feedback')
    Announcement = apps.get_model('general', 'Announcement')
    Guest = apps.get_model('general', 'Guest')

    Feedback.objects.all().delete()
    Announcement.objects.all().delete()
    Guest.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_sample_data, reverse_sample_data),
    ]
