# Generated by Django 5.2.6 on 2025-11-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_announcement_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
