# Generated by Django 5.2.6 on 2025-11-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_announcement_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='slug',
        ),
    ]
