# Generated by Django 5.2.6 on 2025-10-05 00:49

from django.db import migrations
from django.contrib.auth import get_user_model


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
    ]
