# Generated by Django 5.2.6 on 2025-10-04 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('nature', 'Nature'), ('cultural', 'Cultural'), ('historical', 'Historical'), ('food', 'Food'), ('adventure', 'Adventure'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=100, null=True)),
                ('avg_duration_minutes', models.PositiveIntegerField(default=60)),
                ('entrance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_costs', models.TextField(blank=True, null=True)),
                ('budget_category', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('nearest_transport', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_travel_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('parking_available', models.BooleanField(default=False)),
                ('wheelchair_friendly', models.BooleanField(default=False)),
                ('kid_friendly', models.BooleanField(default=False)),
                ('senior_friendly', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Temporarily Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
