# Generated by Django 5.2.6 on 2025-10-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='city',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='region',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='total_reviews',
        ),
    ]
