from django.db import migrations

def seed_destinations(apps, schema_editor):
    Destination = apps.get_model('destination', 'Destination')
    User = apps.get_model('auth', 'User')

    admin = User.objects.filter(is_superuser=True).first()

    sample_data = [
    {
        "name": "Paguriran Island and Lagoon",
        "category": "nature",
        "description": "A scenic island-lagoon with clear waters, ideal for swimming and snorkeling.",
        "address": "Bacon, Sorsogon",
        "latitude": 12.9700,
        "longitude": 124.0500,
        "opening_time": "07:00",
        "closing_time": "17:00",
        "best_time_to_visit": "March-May",
        "avg_duration_minutes": 120,
        "entrance_fee": 50,
        "budget_category": "low",
        "nearest_transport": "Boat from Bacon port",
        "estimated_travel_time_minutes": 30,
        "parking_available": False,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": True,
        "status": "active",
    },
    {
        "name": "Libanon Beach",
        "category": "nature",
        "description": "Quiet, white sand beach in Gubat.",
        "address": "Gubat, Sorsogon",
        "latitude": 12.9200,
        "longitude": 124.1200,
        "opening_time": "06:00",
        "closing_time": "18:00",
        "best_time_to_visit": "December-April",
        "avg_duration_minutes": 180,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "By road from Gubat",
        "estimated_travel_time_minutes": 20,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": True,
        "status": "active",
    },
    {
        "name": "Bulusan Lake",
        "category": "nature",
        "description": "Lush volcanic lake in Bulusan Volcano Natural Park.",
        "address": "Bulusan, Sorsogon",
        "latitude": 12.7516,
        "longitude": 123.8800,
        "opening_time": "05:00",
        "closing_time": "18:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 90,
        "entrance_fee": 30,
        "budget_category": "low",
        "nearest_transport": "From Sorsogon City",
        "estimated_travel_time_minutes": 60,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Bagatao Island Lighthouse",
        "category": "historical",
        "description": "Historic lighthouse on Bagatao Island, guiding ships entering Sorsogon Bay.",
        "address": "Bagatao Island, Magallanes, Sorsogon",
        "latitude": 12.7950,
        "longitude": 123.7850,
        "opening_time": "08:00",
        "closing_time": "17:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 60,
        "entrance_fee": 20,
        "budget_category": "low",
        "nearest_transport": "Boat from Magallanes",
        "estimated_travel_time_minutes": 45,
        "parking_available": False,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Barcelona Coral Church & Ruins Park",
        "category": "cultural",
        "description": "Old coral stone church and ruins in Barcelona, Sorsogon.",
        "address": "Barcelona, Sorsogon",
        "latitude": 12.8680,
        "longitude": 124.1370,
        "opening_time": "06:00",
        "closing_time": "18:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 60,
        "entrance_fee": 10,
        "budget_category": "low",
        "nearest_transport": "Road via Barcelona",
        "estimated_travel_time_minutes": 30,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Sorsogon Capitol Park",
        "category": "cultural",
        "description": "Public park and landmark surrounding the provincial capitol building.",
        "address": "Sorsogon City",
        "latitude": 12.9700,
        "longitude": 124.0000,
        "opening_time": "00:00",
        "closing_time": "23:59",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 30,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "In city center",
        "estimated_travel_time_minutes": 5,
        "parking_available": True,
        "wheelchair_friendly": True,
        "kid_friendly": True,
        "senior_friendly": True,
        "status": "active",
    },
    {
        "name": "Sorsogon Sports Arena",
        "category": "other",
        "description": "New sports facility in Sorsogon City.",
        "address": "Sorsogon City",
        "latitude": 12.9720,
        "longitude": 124.0010,
        "opening_time": "06:00",
        "closing_time": "22:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 60,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "City roads",
        "estimated_travel_time_minutes": 10,
        "parking_available": True,
        "wheelchair_friendly": True,
        "kid_friendly": True,
        "senior_friendly": True,
        "status": "active",
    },
    {
        "name": "Pipa de Playa (Gubat)",
        "category": "nature",
        "description": "Secluded beach spot in Gubat.",
        "address": "Gubat, Sorsogon",
        "latitude": 12.9150,
        "longitude": 124.1150,
        "opening_time": "06:00",
        "closing_time": "18:00",
        "best_time_to_visit": "December-April",
        "avg_duration_minutes": 120,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "By road from Gubat",
        "estimated_travel_time_minutes": 25,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Subic White Beach",
        "category": "nature",
        "description": "White sandy beach popular among local tourists.",
        "address": "Matnog, Sorsogon",
        "latitude": 12.5800,
        "longitude": 124.0850,
        "opening_time": "05:00",
        "closing_time": "19:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 180,
        "entrance_fee": 30,
        "budget_category": "low",
        "nearest_transport": "Road from Matnog",
        "estimated_travel_time_minutes": 60,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Donsol Whale Shark Interaction",
        "category": "adventure",
        "description": "Swim with whale sharks in Donsol (seasonal).",
        "address": "Donsol, Sorsogon",
        "latitude": 12.9100,
        "longitude": 123.6000,
        "opening_time": "08:00",
        "closing_time": "16:00",
        "best_time_to_visit": "December-May",
        "avg_duration_minutes": 240,
        "entrance_fee": 500,
        "budget_category": "medium",
        "nearest_transport": "From Donsol town",
        "estimated_travel_time_minutes": 20,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Lake Aguingay",
        "category": "nature",
        "description": "Seasonal crater lake near Bulusan.",
        "address": "Bulusan, Sorsogon",
        "latitude": 12.7550,
        "longitude": 123.8850,
        "opening_time": "06:00",
        "closing_time": "18:00",
        "best_time_to_visit": "Rainy season",
        "avg_duration_minutes": 120,
        "entrance_fee": 20,
        "budget_category": "low",
        "nearest_transport": "From Bulusan Lake trails",
        "estimated_travel_time_minutes": 45,
        "parking_available": False,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Parola Beach & Lighthouse (Bagatao Island)",
        "category": "nature",
        "description": "Beach area with lighthouse on Bagatao Island.",
        "address": "Bagatao Island, Magallanes, Sorsogon",
        "latitude": 12.7950,
        "longitude": 123.7850,
        "opening_time": "06:00",
        "closing_time": "18:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 90,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "Boat from Magallanes",
        "estimated_travel_time_minutes": 45,
        "parking_available": False,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Pepita Park",
        "category": "cultural",
        "description": "Public park in Sorsogon City.",
        "address": "Sorsogon City",
        "latitude": 12.9690,
        "longitude": 124.0020,
        "opening_time": "00:00",
        "closing_time": "23:59",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 30,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "City roads",
        "estimated_travel_time_minutes": 5,
        "parking_available": True,
        "wheelchair_friendly": True,
        "kid_friendly": True,
        "senior_friendly": True,
        "status": "active",
    },
    {
        "name": "Ilawod Beach",
        "category": "nature",
        "description": "Beach in Sorsogon province.",
        "address": "Matnog, Sorsogon",
        "latitude": 12.5820,
        "longitude": 124.0880,
        "opening_time": "05:00",
        "closing_time": "18:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 180,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "Road from Matnog",
        "estimated_travel_time_minutes": 50,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Rompeolas (Breakwater) Sorsogon City",
        "category": "other",
        "description": "Coastal promenade / breakwater in Sorsogon City.",
        "address": "Sorsogon City",
        "latitude": 12.9680,
        "longitude": 124.0030,
        "opening_time": "00:00",
        "closing_time": "23:59",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 45,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "City roads",
        "estimated_travel_time_minutes": 10,
        "parking_available": False,
        "wheelchair_friendly": True,
        "kid_friendly": True,
        "senior_friendly": True,
        "status": "active",
    },
    {
        "name": "Dancalan Bay / Beach",
        "category": "nature",
        "description": "Peaceful bay and beach in Dancalan area.",
        "address": "Dancalan, Donsol, Sorsogon",
        "latitude": 12.9050,
        "longitude": 123.5980,
        "opening_time": "06:00",
        "closing_time": "18:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 120,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "Road from Donsol",
        "estimated_travel_time_minutes": 60,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "SM City Sorsogon (Mall / Shopping)",
        "category": "shopping",
        "description": "Large mall for shopping in Sorsogon City.",
        "address": "Sorsogon City",
        "latitude": 12.9712,
        "longitude": 123.9295,
        "opening_time": "10:00",
        "closing_time": "21:00",
        "best_time_to_visit": "Evenings / weekends",
        "avg_duration_minutes": 120,
        "entrance_fee": 0,
        "budget_category": "low",
        "nearest_transport": "City roads",
        "estimated_travel_time_minutes": 10,
        "parking_available": True,
        "wheelchair_friendly": True,
        "kid_friendly": True,
        "senior_friendly": True,
        "status": "active",
    },
    {
        "name": "Cultural / Museo Sorsogon",
        "category": "cultural",
        "description": "Local museum showcasing history and culture of Sorsogon.",
        "address": "Sorsogon City",
        "latitude": 12.9700,
        "longitude": 124.0005,
        "opening_time": "08:00",
        "closing_time": "17:00",
        "best_time_to_visit": "All year",
        "avg_duration_minutes": 60,
        "entrance_fee": 20,
        "budget_category": "low",
        "nearest_transport": "City roads",
        "estimated_travel_time_minutes": 5,
        "parking_available": True,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
    {
        "name": "Nasipit Falls",
        "category": "nature",
        "description": "Waterfall in Bulusan area (one of the falls in Bulusan NP).",
        "address": "Bulusan, Sorsogon",
        "latitude": 12.7580,
        "longitude": 123.8920,
        "opening_time": "06:00",
        "closing_time": "17:00",
        "best_time_to_visit": "Rainy season",
        "avg_duration_minutes": 90,
        "entrance_fee": 20,
        "budget_category": "low",
        "nearest_transport": "From Bulusan trails",
        "estimated_travel_time_minutes": 30,
        "parking_available": False,
        "wheelchair_friendly": False,
        "kid_friendly": True,
        "senior_friendly": False,
        "status": "active",
    },
]

    for data in sample_data:
        Destination.objects.create(
            name=data["name"],
            category=data["category"],
            description=data["description"],
            address=data["address"],
            latitude=data["latitude"],
            longitude=data["longitude"],
            opening_time=data["opening_time"],
            closing_time=data["closing_time"],
            best_time_to_visit=data["best_time_to_visit"],
            avg_duration_minutes=data["avg_duration_minutes"],
            entrance_fee=data["entrance_fee"],
            budget_category=data["budget_category"],
            nearest_transport=data["nearest_transport"],
            estimated_travel_time_minutes=data["estimated_travel_time_minutes"],
            parking_available=data["parking_available"],
            wheelchair_friendly=data["wheelchair_friendly"],
            kid_friendly=data["kid_friendly"],
            senior_friendly=data["senior_friendly"],
            status=data["status"],
            created_by=admin,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_remove_destination_average_rating_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_destinations),
    ]