# Generated by Django 5.2.6 on 2025-10-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_auto_20251005_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
