# Generated by Django 5.2.6 on 2025-12-10 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0006_alter_destination_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destinations/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='destination.destination')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
